# Generated by Django 3.0.8 on 2020-09-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='m_name',
            new_name='middle_name',
        ),
    ]
