# Generated by Django 3.1 on 2020-08-31 14:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
                ('teacher_sap_id', models.CharField(default=None, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='SAP ID must be valid', regex='^\\+?6?\\d{10,12}$')])),
                ('subject', models.CharField(max_length=10)),
                ('teachingExperience', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
    ]
