# Generated by Django 3.1 on 2020-09-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200912_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='mcq_exam',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='McqExam',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
