# Generated by Django 3.1 on 2020-09-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_id', models.CharField(max_length=11, verbose_name='sap id')),
                ('f_name', models.CharField(max_length=255, verbose_name='first name')),
                ('l_name', models.CharField(max_length=255, verbose_name='last name')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('is_student', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
