# Generated by Django 3.0.4 on 2020-09-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200910_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.CharField(default='DEfault', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
    ]
