# Generated by Django 3.1 on 2020-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200909_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='check_student',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='check_teacher',
            field=models.BooleanField(),
        ),
    ]
