# Generated by Django 3.1 on 2020-09-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200909_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='check_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='check_teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='check_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='check_teacher',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='check_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='check_teacher',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
