# Generated by Django 3.1 on 2020-09-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200910_1557'),
        ('account', '0006_auto_20200910_1512'),
    ]

    operations = [
    ]
