# Generated by Django 3.1 on 2020-09-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200909_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='check_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='check_teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='check_student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='check_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='check_student',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='check_teacher',
            field=models.BooleanField(null=True),
        ),
    ]
