# Generated by Django 3.1 on 2020-09-10 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200910_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiztakers',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiztakers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='quiztaker',
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions_count',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='roll_out',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
        migrations.AddField(
            model_name='question',
            name='CorrectAnswer',
            field=models.CharField(default='CorrectAnswer', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='QuestionText',
            field=models.CharField(default='QuestionTextDefault', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='Option1', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='Option2', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='Option3', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default='Option4', max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='QuizTakers',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='subject',
            name='taughtBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
        ),
    ]
