# Generated by Django 3.1 on 2020-09-10 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200911_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='CorrectAnswer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='QuestionText',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='name',
        ),
        migrations.AddField(
            model_name='question',
            name='choice1',
            field=models.CharField(default='choice1', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2',
            field=models.CharField(default='choice2', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3',
            field=models.CharField(default='choice3', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='choice4',
            field=models.CharField(default='choice4', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_choice',
            field=models.CharField(default='correct_choice', max_length=30),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='question_text'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.CharField(default='Topic', max_length=30),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='result',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.quiz'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
    ]
